# Details of a user
---
from: 2018-10-01
to: 2019-02-01
taskHeight: 30
taskTopMargin: 5
drawingArea:
  type: area
  x: 144
  y: 108
  width: 432 
  height: 324
labelStyle:
  format: MM-yy
  relativePosition:
    type: area
    x: -30
    y: -30
    width: 60
    height: 20
  lineColor:
    type: name
    code: BLACK  
defaultTaskStyle:
  fontSize: 12
  textAlign: CENTER
  shapeType: CHEVRON
  fillColor:
    type: name
    code: RED
tasks:
- level: 0
  name: a
  from: 2018-10-01
  to: 2018-10-15
- level: 0
  name: c
  from: 2018-10-15
  to: 2018-11-15
- level: 1
  name: b
  from: 2018-10-15
  to: 2018-11-01
  style:
    fillColor:
      type: name
      code: GREEN
- name: aaa
  from: 2018-11-01
  to: 2019-01-15
- name: bbb
  from: 2019-01-15
  to: 2019-02-01
- name: ccc
  from: 2018-11-01
  to: 2019-01-01
